# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181117_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/Users/macbook/Desktop/garlic-farm.jpg', upload_to=''),
        ),
    ]
